version: "3.7"

services:
  node-db:
    container_name: node-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE='risk-assesment'
    ports:
      - 27017:27017

  node-cache:
    container_name: node-cache
    restart: always
    image: 'redis:latest'
    ports:
      - 6379:6379

  node-risk-assesment:
    container_name: node-risk-assesment
    restart: always
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src/
      - ./uploads:/app/uploads/
    ports:
      - 8002:8002

volumes:
  db-config:
  db-data: