version: "3.3"
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '${DATABASE_PORT}:27017'
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      # - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE='${DATABASE_NAME}'
  redis:
    image: 'redis:latest'
    ports:
      - '${CACHE_PORT}:6379'
