version: "3.7"

services:
  node-db:
    container_name: node-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE='${DATABASE_NAME}'
    ports:
      - 27017:27017

  node-cache:
    image: 'redis:latest'
    ports:
      - '${CACHE_PORT}:6379'

  node-risk-assesment:
    container_name: node-risk-assesment
    restart: always
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src/
      - ./uploads:/app/uploads/
    ports:
      - 8002:8002
    depends_on:
      - node-db
      - node-cache
    links:
      - node-db
      - node-cache

volumes:
  db-config:
  db-data:
